### ISSUE TITLE
Does not work over HTTPS (on Heroku)

### ISSUE THREAD

**Issue by TravelingTechGuy** [RafalWilinski/express-status-monitor#7]
Just added the route to an Express app I have deployed to Heroku and I'm getting the following error (repeated every second):

```
Mixed Content: The page at 'https://mysitename.herokuapp.com/status' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mysitename.herokuapp.com:41338/socket.io/?EIO=3&transport=polling&t=LQPzECX'. This request has been blocked; the content must be served over HTTPS.

XMLHttpRequest cannot load http://mysitename.herokuapp.com:41338/socket.io/?EIO=3&transport=polling&t=LQPzECX. Failed to start loading.
```

Can you maybe provide a way to specify whether the Socket.io call be made over HTTPS, or better yet, handle this automatically?

**Comment by RafalWilinski** [comment]
Good point, I'll fix that asap!

**Comment by RafalWilinski** [comment]
Fixed: https://github.com/RafalWilinski/express-status-monitor/commit/5afd9c9a058d505dd0512c67354e4914055b1302

**Comment by TravelingTechGuy** [comment]
Thanks! Have you published the fix to NPM?

**Comment by RafalWilinski** [comment]
I've just pushed version `0.0.7`

**Comment by TravelingTechGuy** [comment]
Cheers mate!

**Comment by TravelingTechGuy** [comment]
Just chjecked the latest version - doesn't work. If I browse to my web site without specifying http/https in the address page, and then add the '/status' route, I get `GET http://www.mysite.com:41338/socket.io/?EIO=3&transport=polling&t=LQQXZPh net::ERR_CONNECTION_REFUSED`

**Comment by dpappa** [comment]
^^ experiencing this issue as well. Firewall is open, but my SSL cert doesn't like this being in http

**Comment by TravelingTechGuy** [comment]
Please reopen the issue. It still occurs. I suspect it may have something to do with the port number, and the way it's specified.

**Comment by RafalWilinski** [comment]
Sorry for that, I'll try to fix that.

**Comment by RafalWilinski** [comment]
Thank you guys for your input and fast reaction! Version `0.0.9` has been published on NPM with HTTPS and HTTP support.

You can test https support here: https://safe-fjord-78017.herokuapp.com/status
